# config.py

# GPIO-konfiguration för NUVARANDE inkoppling
# Ni sa sist att PIR sitter på GPIO 17 och LED på GPIO 27.
GPIO_PIR = 17
GPIO_LED = 27
GPIO_BUZZER = 13
GPIO_DOOR = 18

API_HOST = "0.0.0.0"
API_PORT = 5000
DEBUG = False

POLL_INTERVAL = 0.5
EVENT_LIMIT = 40

ENABLE_BUZZER = True
ENABLE_DOOR_SENSOR = False
DOOR_ACTIVE_IS_OPEN = True

ENABLE_CAMERA = True
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_JPEG_QUALITY = 70
CAMERA_FPS = 5
CAMERA_STARTUP_DELAY = 1.0
CAMERA_IMAGE_PATH = "/tmp/smart_hemlarm_camera.jpg"
ZIGBEE_MQTT_ENABLED = True
ZIGBEE_MQTT_BROKER = "127.0.0.1"
ZIGBEE_MQTT_PORT = 1883
ZIGBEE_MQTT_TOPIC = "zigbee2mqtt/front_door"
